### PR TITLE
docs: Add spanish translation

### PR DESCRIPTION
**Pull request by nothingbutlucas**
Hi there well, here I translated the web page into Spanish.

Maybe we can at least start translating the manual, what do you think?

Thanks!

### CODE REVIEW

**Comment by markqvist** [comment]
Wow, amazing, that was fast! Thank you so much, this will help a lot of people!

My only concern about starting to translate the manual, is that I've been wanting to do some restructuring of the chapters, but I've been saying that for a long time now, and haven't gotten around to it yet anyways. So maybe it's just better to start out on the translation, if you are up for it. I just don't want to waste anybodies work, if I then start rewriting stuff in a couple of months, and the translation needs to be updated.

But in either case, it's better that there *is* a Spanish version than none at all. So if you're okay with all of that, I'd very much appreciate the help on the translation!

**Comment by markqvist** [comment]
I'll push this to the live website as soon as I can.

**Comment by nothingbutlucas** [comment]
Great!
So, I think that [this](https://github.com/markqvist/Reticulum/tree/master/docs/source) are the files of the manual, right?
We also need some kind of menu in the index.html to be able to go through the (hopefully) different languages of the manual, what do u think?

**Comment by markqvist** [comment]
Yes, the rst files are the sources. I'm actually not sure how to best go about the language switching. The build system uses Sphinx (which internally uses LaTeX) to compile the manual to various output formats, such as PDF, EPUB and HTML. Maybe Sphinx itself has some support functions for multilingual setups build into it. If it does, I think it is worth using that.

**Pull request merged**
